### ISSUE TITLE
Add more examples to the documentation.

### ISSUE THREAD

**Issue by Lubba-64** [Lubba-64/inventory-rs#6]
There absolutely should be more examples for this crate in the documentation, or we should just move a bunch of the tests to docstrings. my only issue is that the tests can be kind of verbose because of all of the specific checks that have to be done, so I'm not super sure what the best way to approach this is.

**Comment by maccesch** [comment]
I think there should be examples in the readme as well. At least for basic usage.

**Comment by Lubba-64** [comment]
> I think there should be examples in the readme as well. At least for basic usage.

Agreed, I can pretty easily include that in #8
